# Generated by Django 3.1.4 on 2021-03-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20210330_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleitor',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vote', to='voting.vote'),
        ),
    ]
