# Generated by Django 3.1.4 on 2021-03-31 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20210330_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='eleitor_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleitor_vote', to='voting.eleitor'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='item_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_vote', to='voting.item'),
        ),
    ]
